networks:
  app_net:
    driver: bridge

volumes:
  db_data:
  uploads_data:

services:

  db:
    image: postgres:17
    container_name: app_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_net

  redis:
    image: redis:7
    container_name: app_redis
    restart: unless-stopped
    networks:
      - app_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_backend
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
      - uploads_data:/app/uploads
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      UPLOAD_DIR: ${UPLOAD_DIR}
    depends_on:
      - db
      - redis
    networks:
      - app_net

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alembic_migrator
    restart: "no" # Do not restart automatically
    command: ["alembic", "upgrade", "head"]
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app_net


  nginx:
    image: nginx:latest
    container_name: app_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - app_net
