"""Update tables

Revision ID: b5f2aabd6182
Revises: 2950019d2d28
Create Date: 2025-09-01 12:07:13.170698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f2aabd6182'
down_revision: Union[str, None] = '2950019d2d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('projects', 'description')
    # ### end Alembic commands ###
